# Generated by Django 3.1.4 on 2020-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=128)),
                ('_des', models.CharField(max_length=1024)),
                ('_type', models.IntegerField(default=0)),
                ('_url', models.CharField(max_length=512)),
            ],
        ),
    ]
