# Generated by Django 3.1.4 on 2020-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=256)),
                ('_avt', models.CharField(max_length=512)),
                ('_teacher', models.CharField(max_length=64)),
                ('_ta1', models.CharField(max_length=64)),
                ('_ta2', models.CharField(max_length=64)),
                ('_description', models.CharField(max_length=512)),
                ('_syllabuses', models.CharField(max_length=1024)),
            ],
        ),
    ]
